### ISSUE TITLE
Big Dipper NFT Purchase Tablet Errors 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#884] opened 2022-08-25 15:14 UTC
## Summary of Bug

Galaxy not working as expected 
When user is clicking on shared NFT- White Screen is Appears.

![Galaxy A8  Error](https://user-images.githubusercontent.com/93543576/186702863-dcfa1784-a081-459a-bd38-7e1e1fcb4b45.jpg)

iPad not working as Expected 
When user is clicking on shared NFT- NFT is cut off 

![iPad Big Dipper Error ](https://user-images.githubusercontent.com/93543576/186703951-0debfeb3-f3ba-471a-80a9-8f65a0640586.PNG)

## Steps to Reproduce
1.User clicks on shared NFT 
2.User is directed to NFT
3. User lands on NFT

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment] 2022-08-25 15:34
Samsung  it is not working, @abdullahjankhan1 any way to get logs on mobile

**Comment by Tanyaml** [comment] 2022-08-25 21:48
@faisalnaveedRNS  I have tested this again on Galaxy A8- and NFT can be preview but still it not working as expected.
The NFT wire frame is cut off.

Please see video:

https://user-images.githubusercontent.com/93543576/186775057-f628d98f-4a83-4cb7-9a29-1e7744d21ddf.mov

**Comment by faisalnaveedRNS** [comment] 2022-08-26 14:36
not able to reproduce yet

**Comment by StefanB90** [comment] 2022-08-31 15:35
@Tanyaml has confirmed this is working as expected and can close this issue.

**Closed by StefanB90** 2022-08-31 15:35 UTC
Labels: bug, bigdipper
