### ISSUE TITLE
Trying to Purchase NFT using USD, Stripe Server accepts the payment and it fails on the Chain Side.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#775] opened 2022-08-10 21:53 UTC
We are able to enter the test card and it submits and says payment went through and gives the next screenshot error with Memory Issue from Chain.
![Stripe Payment Fail from the chain after putting Test Card In](https://user-images.githubusercontent.com/93538775/184047851-7300d68e-a8d4-4020-9530-1d6263217cdc.png)

## Steps to Reproduce

1-Click on a NFT from the app that's priced in USD.
2- Swipe right to pay.
3- Enter the card number.
4-Wait for the approval.
5-Screen appears.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by abdullahjankhan1** [comment] 2022-08-11 10:33
@mustafapylons @MikeSofaer @faddat 
The issue that we are facing is from our blockchain.
Reason: When the validators updated to the new version of our blockchain their ParamSpace was already set with our old naming convention, i.e. camel case, now the issue is that we expect to receive our params in snake_case format while the result of a query from blockchain is in form of camel case.
This issue was handled in our stripe server but now we get the same issue in our blockchain when we buy an NFT with stripe USD to verify the receipt and calculation of the fee we need that same information, thus causing a panic after purchase.

This is something to be upgraded with the upgrade handlers or someway until then we are blocked for stripe purchases.

Expected vs Receiving responses are attached below:
- Response We Are Getting
[{\"CoinDenom\":\"ustripeusd\",\"pubKey\":\"EVK1dqjD6K8hGylacMpWAa/ru/OnWUDtCZ+lPkv2TTA=\",\"processorPercentage\":\"0.000000000000000000\",\"validatorsPercentage\":\"0.003000000000000000\",\"name\":\"Pylons_Inc\"}]


- Response Expected From The Updated Code
[{\"coin_denom\":\"ustripeusd\",\"pub_key\":\"EVK1dqjD6K8hGylacMpWAa/ru/OnWUDtCZ+lPkv2TTA=\",\"processor_percentage\":\"0.000000000000000000\",\"validators_percentage\":\"0.003000000000000000\",\"name\":\"Pylons_Inc\"}]

**Comment by abdullahjankhan1** [comment] 2022-08-24 04:26
This issue is fixed in:
PR# https://github.com/Pylons-tech/pylons/pull/783

**Comment by StefanB90** [comment] 2022-08-31 16:10
This issue will be resolved after the next chain upgrade. Until that time, we will keep it open.

**Comment by Tanyaml** [comment] 2022-09-16 02:59
@StefanB90 @faisalnaveedRNS what is the status on this?

**Comment by StefanB90** [comment] 2022-09-21 16:32
To be released on 9/23 w/ chain upgrade

cc @MikeSofaer @mustafapylons @faisalnaveedRNS

**Comment by faisalnaveedRNS** [comment] 2022-10-28 04:45
@ahmadrns is it fixed

**Comment by ahmadrns** [comment] 2022-11-01 04:28
@faisalnaveedRNS yes, it is fixed. This issue is fixed in https://github.com/Pylons-tech/pylons/pull/1319

**Closed** 2022-11-22 20:52 UTC
Labels: chain, [zube]: To Do
