### ISSUE TITLE
Fix zoom level of image view within Pylons app

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#924] opened 2022-08-30 14:55 UTC
## Summary of Bug

Per Mike, we must prioritize fixing the zoom level on the view of images in the app. You should be able to see the whole image of the NFT in the full screen NFT view.

On mobile, I should be able to see the entire image of a NFT whether I'm in the Big Dipper mobile browser view or whether I'm in the Pylons app.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment] 2022-09-14 05:52
@Tanyaml please test this.
@kjawadDeveloper2

**Comment by Tanyaml** [comment] 2022-09-15 16:09
@faizhashmiRnS I am still not seeing full image on Mobile of the following NFT.
https://latest---bigdipper-jhv3rfpllq-uc.a.run.app/?recipe_id=Easel_Recipe_auto_recipe_2022_09_13_125805_803&cookbook_id=Easel_CookBook_auto_cookbook_2022_09_13_125802_831&address=pylo1kstu9dgfxjfe33h6jjg8zruneddcecwwj9dd0x

Please see screenshot:
![Screenshot_20220915-115807](https://user-images.githubusercontent.com/93543576/190453300-a83d71e6-04b7-48d1-8415-8eb612d8a194.png)

**Comment by faizhashmiRnS** [comment] 2022-09-16 05:25
HI @Tanyaml, I believe you do not have the latest code. Please test it on the build that I will share it with you today.

**Comment by Tanyaml** [comment] 2022-09-16 14:28
hi @faizhashmiRnS This is working as expected although I can not publish the NFT I am gettin the following error:
1. When user is trying to crop image it is very sensitive to the arrows that direct you back to the image upload screen.

https://user-images.githubusercontent.com/93543576/190662343-2431cbbc-ec8f-4bb1-b8f2-333f8e9af7ae.mov




3. When user is trying to Publish this error occurs: Cookbook parsing failed

Uploading Cookbook parsing failed.mov…

**Comment by Tanyaml** [comment] 2022-09-16 14:43
@faizhashmiRnS  This is still not working as expected when user clicks on shared NFT ---> user is directed to Big Dipper and this is where the image is not valid, then user clicks on buy NFT and then is direct to purchase NFT  where the correct format image is previewed.
Therefore the Big Dipper has the issue for the aspect ratio for the Image.

Please video:


https://user-images.githubusercontent.com/93543576/190665899-b78e25d8-3665-4e04-b022-0e7efcfbdacc.mov

**Comment by Tanyaml** [comment] 2022-09-17 13:56
@kjawadDeveloper2 

As tested before and testing again with the Build given on Friday 
(https://we.tl/t-J0VfVTXRIi)
(https://we.tl/t-aV2gKOuo09)

This is still not working as expected when user clicks on shared NFT ---> user is directed to Big Dipper and this is where the image is not valid, then user clicks on buy NFT and then is direct to purchase NFT where the correct format image is previewed.
Therefore the Big Dipper has the issue for the aspect ratio for the Image.

Please see video:

https://user-images.githubusercontent.com/93543576/190860692-42137371-3acd-4607-b7a7-5ca4ba7abe9e.mov

**Comment by faizhashmiRnS** [comment] 2022-09-19 05:24
Hi @Tanyaml , The link you clicked seem to be an old link which will definitely direct us to the big dipper first. In order to test this we need to create a new NFT link which should be a shorter link something like **https://pylons.page.link/VzTVstkAQyWmaTos6**
Please try this and let me know if anything goes wrong.

**Comment by Tanyaml** [comment] 2022-09-19 15:59
@faizhashmiRnS  This is still not working as expected- Th image in Pylons app is still not as expected when user lands on Big Dipper.

Please see video:


https://user-images.githubusercontent.com/93543576/191061182-638cfe37-ea81-471a-b243-80cfc7da2825.mov

**Comment by Tanyaml** [comment] 2022-09-19 17:37
I will be closing this ticket- since it image preview in Pylons app is working as expected. Although the issue is with BD- I will be opening a bug for this issue.

**Comment by kjawadDeveloper2** [comment] 2022-09-19 18:32
@faizhashmiRnS we discussed that you will be sending separate PRs because the branch code was not good. Kindly send a separate small PR for this. Then we can close this.

**Comment by faizhashmiRnS** [comment] 2022-09-20 04:25
> @faizhashmiRnS we discussed that you will be sending separate PRs because the branch code was not good. Kindly send a separate small PR for this. Then we can close this.

Sure.

**Closed** 2022-09-20 15:11 UTC
Labels: bug, test, mobile, critical, closed, [zube]: Done
