### ISSUE TITLE
Using Chrome 105 version, the blog site doesn't load anymore (desktop) 

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#956] opened 2022-09-01 17:29 UTC
## Summary of Bug

Using Chrome 105 version, the blog site doesn't load anymore (desktop)

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment] 2022-09-01 17:30
screenshot for context 
![Screen Shot 2022-09-01 at 10 30 38 AM](https://user-images.githubusercontent.com/74597290/187976547-22bf2da4-105c-4818-b9f4-9e7c65387864.png)

**Comment by faisalnaveedRNS** [comment] 2022-09-01 17:42
Working fine on version 99, updating my chrome version, to check on latest one

**Comment by faisalnaveedRNS** [comment] 2022-09-01 17:49
unable to reproduce, on version 105

**Comment by faisalnaveedRNS** [comment] 2022-09-01 17:50
@heyitsjk need more information on this

**Comment by heyitsjk** [comment] 2022-09-05 07:33
closing this issue as it's not reproducible on my other machines running 105

**Closed by heyitsjk** 2022-09-05 07:33 UTC
Labels: website
